spring.datasource.url=jdbc:postgresql://ep-sparkling-morning-b5dep9zh-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_SmaXztV1s9bM
spring.datasource.driver-class-name=org.postgresql.Driver

# Spécifier explicitement le dialecte PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Gestion automatique des tables JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true